### config ###

# See https://www.mkdocs.org/user-guide/configuration/.

INHERIT: !ENV MKDOCS_BASE_CONFIG

site_name: Documentação do Prometheus
site_description: Documentação do Prometheus

### navigation ###

nav:
  - index.md
  - introducao/visao-geral.md
